version: '3.2'
services:

    # https://github.com/portainer/portainer
    # https://hub.docker.com/r/portainer/portainer/
    portainer:
        image: "portainer/portainer:linux-arm"
        volumes:
            - config_vol:/data
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "9000:9000"
        env_file:
            - ./portainer.env
        networks:
            - overlay_net

volumes:
    config_vol:

networks:
    overlay_net:
        driver: overlay
